site_name: FAIR-by-Design Training for CLARIN Community
docs_dir: resources
theme:
  name: material
  palette:
    primary: custom
  logo: attachments/logo.png
  custom_dir: resources/overrides
  features:
    - navigation.footer
    - search.highlight
    - search.suggest
markdown_extensions:
  - attr_list
  - markdown_include.include:
      base_path: .
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
plugins:
  - search
  - tags
  - mike:
      version_selector: true
  - exclude:
      glob:
        - "*Activities/*"
        - "*Assessment/*"
        - "*Templates/*"
        - "*Feedback/*"
        - "*.tmp"
        - "*.pdf"
        - "*.gz"
        - "*.pptx"
        - "*_plan.md"
        - "*facilitator_guide.md"
        - "*syllabus.md"
      regex:
        - '.*\.(tmp|bin|tar)$'
extra:
  version:
    provider: mike
extra_css:
  - stylesheets/extra.css
citation:
  cff-version: 1.2.0
  message: "If you use these learning materials, please cite it as below."
  authors:
    - family-names: Filiposka
      given-names: Sonja
      orcid: https://orcid.org/0000-0003-0034-2855
      affiliation: UKIM
    - family-names: Mishev
      given-names: Anastas
      orcid: https://orcid.org/0000-0001-7271-6655
      affiliation: UKIM
    - family-names: Anastasopoulou
      given-names: Athina
      affiliation: GRNET
    - family-names: Frontini
      given-names: Francesca
      orcid: https://orcid.org/0000-0002-8126-6294
      affiliation: CLARIN ERIC
    - family-names: Pedonese
      given-names: Giulia
      orcid: https://orcid.org/0000-0003-3828-0135
      affiliation: CLARIN
    - family-names: van der Lek
      given-names: Iulianna
      orcid: https://orcid.org/0000-0002-0736-0311
      affiliation: CLARIN
  title: "FAIR-by-Design training for the CLARIN community"
  abstract: "When developing learning materials, it is essential to ensure they are FAIR (Findable, Accessible, Interoperable, and Reusable) from both the learners' and trainers' perspectives. Therefore, integrating FAIR principles into the development of learning materials is a crucial element. This training introduces the CLARIN community to the FAIR-by-Design Methodology, which provides a systematic approach that embeds the FAIR principles into the backward instructional design process."
  version: 1.0.1
  doi: 10.5281/zenodo.13867278
  date-released: "2024"
  license: CC-BY-4.0
  license-url: "https://creativecommons.org/licenses/by/4.0/legalcode.txt"
  type: generic
  keywords:
    - FAIR learning materials
    - FAIR-by-Design methodology
    - FAIR instructional design
    - FAIR quality assessment
  repository: "https://github.com/FAIR-by-Design-Methodology/CLARIN-Training"
signposting_linkset: https://raw.githubusercontent.com/FAIR-by-Design-Methodology/CLARIN-Training/1.0.1/linkset.json # do not update manually
signposting_default_profile: '' # update with an URL towards the profile used for the Markdown pages (optional)
# signposting_gitbook_url: https://gitbook.example.com # leave commented (prefixed with `#`) if using GitHub Pages with the default domain.
signposting_exclusions:
  - 'venv/**'
  - 'external-resources/**'
  - 'Feedback/**'
  - '**/Activities/**'
  - '*/Assessment/**'
  - 'index.md'
  - '02 process_description.md'
  - '03 glossary.md'
  - 'template_unit_lesson_plan.md'
  - '**/*facilitator_guide.md'
  - '*syllabus.md'
  - '**/*_plan.md'
  - '**/template_content.md'
